[service]
ip = "0.0.0.0"
port = 8090
wsproxy.url = ""
mode = "webui"
enable_signup = false
allow_anonymous_change_password = false
allow_project_resource_monitor = false
allow_change_signin_mode = false
allow_manual_image_name_for_session = false
allow_signup_without_confirmation = false
always_enqueue_compute_session = false
webui_debug = true
mask_user_info = false
enable_2FA = false
force_2FA = false
directory_based_usage = false
enable_reservoir = false

[resources]
open_port_to_public = false
allow_non_auth_tcp = false
allow_preferred_port = false
max_cpu_cores_per_container = 64
max_memory_per_container = 64
max_cuda_devices_per_container = 16
max_cuda_shares_per_container = 16
max_shm_per_container = 2
max_file_upload_size = 4294967296

[security]
request_policies = ["reject_metadata_local_link_policy", "reject_access_for_unsafe_file_policy"]
response_policies = ["set_content_type_nosniff_policy"]

[environments]

[plugin]

[pipeline]
endpoint = "http://127.0.0.1:9500"
frontend-endpoint = "http://127.0.0.1:3000"

[ui]
menu_blocklist = "pipeline"

[api]
domain = "default"
endpoint = "http://127.0.0.1:8081"
text = "Backend.AI (Docker Dev)"
ssl_verify = false
auth_token_name = 'sToken'

[session]

[session.redis]
addr = "127.0.0.1:8110"

[session.redis.redis_helper_config]

max_age = 604800
flush_on_startup = false
login_block_time = 1200
login_allowed_fail_count = 10
max_count_for_preopen_ports = 10

[webserver]

[logging]
level = "DEBUG"
drivers = ["console"]

[logging.console]
colored = true
format = "verbose"

[logging.pkg-ns]
"" = "WARNING"
"aiotools" = "INFO"
"aiohttp" = "INFO"
"ai.backend" = "DEBUG"

[debug]
enabled = true

[otel]
enabled = false

[apollo-router]
enabled = true
endpoint = "http://127.0.0.1:4000"

# vim: ft=toml
