{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-ai.fullname" . }}
  labels:
    {{- include "backend-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  BA_DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
{{- end }}
